# Generated by Django 5.2.8 on 2025-12-03 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='رقم عملية Paylink')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('INITIATED', 'تم البدء'), ('PENDING_PAYLINK', 'قيد انتظار Paylink'), ('COMPLETED', 'اكتمل بنجاح'), ('FAILED', 'فشل')], default='INITIATED', max_length=20, verbose_name='حالة الدفع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rental_booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='bookings.booking', verbose_name='الحجز المرتبط')),
            ],
        ),
    ]
