# Generated by Django 5.2.8 on 2025-12-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم السيارة')),
                ('model_year', models.IntegerField(verbose_name='الموديل')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='رقم اللوحة')),
                ('color', models.CharField(max_length=20, verbose_name='اللون')),
                ('transmission', models.CharField(choices=[('auto', 'أوتوماتيك'), ('manual', 'عادي')], default='auto', max_length=10, verbose_name='ناقل الحركة')),
                ('fuel_type', models.CharField(choices=[('petrol', 'بنزين'), ('diesel', 'ديزل'), ('hybrid', 'هجين'), ('electric', 'كهرباء')], default='petrol', max_length=10, verbose_name='نوع الوقود')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر اليومي')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='صورة السيارة')),
                ('is_available', models.BooleanField(default=True, verbose_name='متاحة للإيجار؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
