# Generated by Django 5.2.8 on 2025-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='color',
        ),
        migrations.RemoveField(
            model_name='car',
            name='fuel_type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='car',
            name='model_year',
        ),
        migrations.RemoveField(
            model_name='car',
            name='name',
        ),
        migrations.RemoveField(
            model_name='car',
            name='plate_number',
        ),
        migrations.RemoveField(
            model_name='car',
            name='transmission',
        ),
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default=1, max_length=50, verbose_name='الشركة المصنعة'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default='Unknown', verbose_name='الوصف'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='model_name',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='الموديل'),
            preserve_default=False,
        ),
    ]
