# Generated by Django 5.2.8 on 2025-12-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='duration_days',
            field=models.IntegerField(default=0, verbose_name='مدة الحجز بالأيام'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='السعر الإجمالي'),
        ),
    ]
